#undef SPHINCS_N
#undef SPHINCS_H
#undef SPHINCS_D
#undef SPHINCS_K
#undef SPHINCS_A
#undef sphincs_hash_h_msg
#undef sphincs_hash_prf
#undef sphincs_hash_prf_msg
#undef sphincs_hash_f
#undef sphincs_hash_h
#undef sphincs_hash_t
#undef sphincs_fors_msg_to_indices
#undef sphincs_fors_tree_sign_and_pk
#undef sphincs_fors_sign_and_pk
#undef sphincs_fors_sig_to_pk
#undef sphincs_wots_gen_key
#undef sphincs_wots_gen_pk
#undef sphincs_wots_sign_and_pk
#undef sphincs_wots_sig_to_pk
#undef sphincs_xmss_gen_pk
#undef sphincs_xmss_sign_and_pk
#undef sphincs_xmss_sig_to_pk
#undef sphincs_ht_gen_pk
#undef sphincs_ht_sign
#undef sphincs_ht_sig_to_pk
#undef sphincs_gen_key
#undef sphincs_sign
#undef sphincs_verify
